blogapp/urls.py
from django.urls import path
from.import views
from .views import PostList,PostDetail
from django.contrib.auth.decorators import login_required


app_name = 'blogapp'


urlpatterns = [
	
	path('',views.home,name='home'),
	path('newposts',PostList.as_view(),name='postlist'),
	path('newposts/<slug:slug>',PostDetail.as_view(),name='postdetail'),
	#path('profile/<int:pk>/<uuid:uuid>',login_required(views.ProfileDetail.as_view()),name='profile'),
	#path('login',views.login,name='login'),
	path('register',views.register,name='register'),
	path('contact',views.contact,name='contact'),

	#path('profile/<int:pk>/editprofile/<uuid:uuid>',login_required(views.EditProfileForm),name='editprofile'),	
	#path('logout',views.logout,name="logout"),
	path('search',views.search,name='search'),


	
]

projects/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-admin-what-is-the-true-nature-of-the-universe/', admin.site.urls),
    path('',include("blogapp.urls")),


    
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/contact.html
{% extends 'index.html' %}

{% block content %}
<div style="background-color: hsl(0,0%,90%);">

<h1>Contact us</h1>
	
</div>
{% endblock %}

templates/home.html
{% extends 'index.html' %}

{% block content %}

{% for object in objects %}

<div class="item mb-5">
  <div class="media">

    <img class="mr-3 img-fluid post-thumb d-none d-md-flex" src="{{object.img.url}}" alt="image">

    <div class="media-body">
      <h3 id='title' style="font-weight: 500;" class="title mb-1"><a style="color: #306998;" href="{% url 'blogapp:postdetail' object.slug %}">{{object.title|title}}</a></h3>
      <div class="meta mb-1"><span class="date">{{object.timestamp}}</span></div>
      
  
      <div class="intro">{{object.intro|safe}}<a href="{% url 'blogapp:postdetail' object.slug %}">...Read more</a></div>

    </div><!--//media-body-->
  </div><!--//media-->
</div><!--//item-->

{% endfor %}

{% endblock %}

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>BLog</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
  
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">


</head> 
 
<body>
 
    <header class="header text-center">     
     
         <h1 class="blog-name pt-lg-4 mb-0"><a style="font-family: Arial;" href="/">PyGramme</a></h1>
      <nav class="navbar navbar-expand-lg navbar-dark" >
           
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navigation" class="collapse navbar-collapse flex-column" >
        <div class="profile-section pt-3 pt-lg-0">

          <ul class="social-list list-inline py-3 mx-auto">
            <li class="list-inline-item"><a href="https://instagram.com/si_the_art_h"><i class="fab fa-instagram fa-fw"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
            <li class="list-inline-item"><a href="https://github.com/sidharth72"><i class="fab fa-github-alt fa-fw"></i></a></li>
   
        </ul>
   
              <hr> 
        </div><!--//profile-section-->
        
        <ul class="navbar-nav flex-column text-left">

        

          <li class="nav-item">
              <h5><a  class="nav-link" href="/">Home</a></h5>
          </li>

          <!--<li class="nav-item">
              <h5><a  class="nav-link" href="/login">Sign in</a></h5>
          </li>-->
          <li class="nav-item">
              <h5><a class="nav-link" href="/register">Subscribe</a></h5>
          </li>

          <li class="nav-item">
              <h5><a class="nav-link" href="/newposts">Recent posts</a></h5>
          </li>

          <li class="nav-item">
              <h5 style="margin-top: 60px;"><a class="nav-link" href="#">About</a></h5>
          </li>

          <li class="nav-item">
              <h5><a class="nav-link" href="contact">Contact</a></h5>
          </li>

         

      </ul>

        
        <div class="my-2 my-md-3">
              
          
          </ul>
          
        </div>
      </div>
    </nav>
    </header>
    
    <div class="main-wrapper">

       <h1 style="font-weight: 700;text-align: center;font-size:60px;padding-top: 5px;padding-bottom: 0px;"><a class="blog-name2" style="font-family: monospace;color: #306998" href="/"><span style="color: #FFE873;">Py</span><span style="color: #306998 ">Gramme</span></a></h1>

              
          <form style="margin-top: 20px;margin-right: 10px; margin-left: 20px;" action="/search" method="get">
                
                        <label class="sr-only" for="semail">Search</label>
                        <input style="background-color:hsl(0,0%,90%);border-radius: 5px;padding:25px;border: solid thick;border-color:white;font-size: 16px;font-weight: 500;;" type="text" id="semail" name="search" class="form-control" placeholder="Search here ... posts , Keywords .. hit enter">
                
                </form><br>
      
      <section class="blog-list px-3 py-5 p-md-5">
        <div class="container">


          {% block content %}

          {% endblock %}

        </div>
      </section>
      
      <footer class="footer text-center py-2 theme-bg-dark">
       
          <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
                <p><span style="font-size: 20px;color: #306998;">©</span><span style="color: #306998;"> Copyrights 2021 - 2023</span><span style="color:#FFE873 ;font-weight: 600;"> pygramme.org</span></p>
                
       
      </footer>
    
    </div><!--//main-wrapper-->
    
    
    
    
    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->  


    
       
    <!-- Javascript -->          
    <script src="{% static 'plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/popper.min.js' %}"></script> 
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script> 

    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'js/demo/style-switcher.js' %}"></script>     
    

</body>
</html> 

templates/login.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Subscribe</title>

    </head>

{% extends 'index.html' %}

{% block content %}

  <div style='width: auto;box-shadow: 5px 5px 50px hsl(0,0%,90%);padding-top: 25px;padding-bottom: 25px;'>
    <form id='login-form' action="login" method="post">
      {% csrf_token %}
      <div class="container">
        <a href="register" style="position: absolute;right: 0;align-items: right;margin-right:40px;font-size: 14px;">Sign up insted</a>
        <h1 style="font-weight: bolder;color: hsl(0,0%,20%);">Sign-in</h1>

        <hr>

          <!--<label for="psw"><b>Username or email</b></label>
          <input type="text" placeholder="Enter Usename" name="username" id="psw" required>-->
  

          <label for="email"><b>Email</b></label>
          <input style="border-radius: 0px;padding: 25px;background-color: hsl(0,0%,90%);" class="form-control" type="text" placeholder="Enter Email" name="login_username" id="email">


          <label for="psw"><b>Password</b></label>
          <input style="border-radius: 0px;padding: 25px;background-color: hsl(0,0%,90%);" class="form-control" type="password" placeholder="Enter Password" name="login_password" id="password" required>

        <hr>
        {% for message in messages %}
        <p style="font-size: 15px;font-weight: 400;color: tomato;">{{message}}</p>
        {% endfor %}

   
        <button type="submit" class="btn btn-primary">Login</button>
        </div><br><br>

  <div class="container signin">
    <p>Dont have an account yet? <a href="register">Signup</a>.</p>
  </div>
</form>
</div>



{% endblock %}

</html>

templates/postview.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>{{object.title}}</title>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Blog Template">
    <meta name="author" content="Xiaoying Riley at 3rd Wave Media">    
    <link rel="shortcut icon" href="favicon.ico"> 
  
    <!-- FontAwesome JS-->
    <script defer src="https://use.fontawesome.com/releases/v5.7.1/js/all.js" integrity="sha384-eVEQC9zshBn0rFj4+TU78eNA19HMNigMviK/PU/FFjLXqa/GKPgX58rvt5Z8PLs7" crossorigin="anonymous"></script>
    
    <!-- Theme CSS -->  
    <link id="theme-style" rel="stylesheet" href="{% static 'css/theme-1.css' %}">


</head> 

<body>
    
    <header class="header text-center">  
     <h1 class="blog-name pt-lg-4 mb-0"><a style="font-family: Arial;" href="/">PyGramme</a></h1>   
        
      <nav class="navbar navbar-expand-lg navbar-dark" >
           
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div id="navigation" class="collapse navbar-collapse flex-column" >
        <div class="profile-section pt-3 pt-lg-0">

          
          <ul class="social-list list-inline py-3 mx-auto">
            <li class="list-inline-item"><a href="#"><i class="fab fa-instagram fa-fw"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
            <li class="list-inline-item"><a href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
   
        </ul>
   
              <hr> 
        </div><!--//profile-section-->
        
        <ul class="navbar-nav flex-column text-left">
        

          <li class="nav-item">
              <h5><a  class="nav-link" href="/">Home</a></h5>
          </li>

         <!-- <li class="nav-item">
              <h5><a  class="nav-link" href="/login">Sign in</a></h5>
          </li>-->
          <li class="nav-item">
              <h5><a class="nav-link" href="/register">Subscribe</a></h5>
          </li>

          <li class="nav-item">
              <h5><a class="nav-link" href="/newposts">Recent Posts</a></h5>
          </li>

          <li class="nav-item">
              <h5 style="margin-top: 60px;"><a class="nav-link" href="#">About</a></h5>
          </li>

          <li class="nav-item">
              <h5><a class="nav-link" href="#">Contact</a></h5>
          </li>

         

      </ul>

        

      </div>
    </nav>
    </header>
    


          {% block content %}

          {% endblock %}

     

      
      <footer class="footer text-center py-2 theme-bg-dark">
       
          <!--/* This template is released under the Creative Commons Attribution 3.0 License. Please keep the attribution link below when using for your own project. Thank you for your support. :) If you'd like to use the template without the attribution, you can buy the commercial license via our website: themes.3rdwavemedia.com */-->
          <p><span style="font-size: 20px;color: #306998;">©</span><span style="color: #306998;"> Copyrights 2021 - 2023</span><span style="color:#FFE873 ;font-weight: 600;"> pygramme.org</span></p>
      </footer>
    
    </div><!--//main-wrapper-->
    
    
    
    
    <!-- *****CONFIGURE STYLE (REMOVE ON YOUR PRODUCTION SITE)****** -->  


    
       
    <!-- Javascript -->          
    <script src="{% static 'plugins/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'plugins/popper.min.js' %}"></script> 
    <script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"></script> 

    <!-- Style Switcher (REMOVE ON YOUR PRODUCTION SITE) -->
    <script src="{% static 'js/demo/style-switcher.js' %}"></script>     
    

</body>
</html> 

templates/register.html
<!DOCTYPE html>
<html lang="en"> 
<head>
    <title>Subscribe</title>

    </head>

{% extends 'index.html' %}

{% block content %}


  <div class="reg-form" style='width: auto;box-shadow: 5px 5px 50px hsl(0,0%,90%);padding-top: 25px;padding-bottom: 25px;'>
    <form id='register-form' action="register" method="post">
      {% csrf_token %}
      <div class="container">
        <h1 style="font-weight: bolder;color: #306998;">Subscribe</h1>
        <p>Please fill in this form to Subscribe.</p>
        <hr>


          <label for="psw"><b style="color: grey;font-weight: 500;font-size: 17px;">First name -</b></label>
          <input  style="border-radius: 0px;padding: 20px;font-size: 15px;border: solid white;border-left-color: #306998;background-color: hsl(0,0%,95%);" class='form-control' type="text" placeholder="Enter firstname" name="first_name" id='firstname-reg'  required>


          <label for="psw"><b style="color: grey;font-weight: 500;font-size: 17px;">Last name -</b></label>
          <input  style="border-radius: 0px;padding: 20px;font-size: 15px;border: solid white;border-left-color: #306998;background-color: hsl(0,0%,95%);" class='form-control' type="text" placeholder="Enter lastname" name="last_name" id='lastname-reg'> 

          <label for="psw"><b style="color: grey;font-weight: 500;font-size: 17px;">Email -</b></label>
          <input  style="border-radius: 0px;padding: 20px;font-size: 15px;border: solid white;border-left-color:#306998;background-color: hsl(0,0%,95%);" class='form-control' type="text" placeholder="Enter Your Email" name="username" id="username-reg" required>

          <p id="username-val"></p>
  
        <hr>
        {% for message in messages %}
        <p style="font-size: 15px;font-weight: 400;color: tomato;">{{message}}</p>
        {% endfor %}
   
       
        <button id='sub-btn' type="submit" class="btn btn-info">Subscribe</button>
        </div>

  <div class="container signin">
  </div>
</form>

</div>


{% endblock %}

templates/search.html
{% extends 'index.html' %}

{% block content %}



<div style="border: solid white;" class="card">
  <div style="background-color: white;" class="card-header">
    Search results:{{results}} {{search}}
  </div>


  <div class="card-body">
{% for search_data in search_datas %}

{% if search in search_data.title or search in search_data.blog %}


    <a style="font-size: 25px;font-weight: 600;color: #306998;" href="{% url 'blogapp:postdetail' search_data.slug %}" class="card-title">⚫ {{search_data.title|title}}</a>
    <p class="card-text">{{search_data.intro|safe}}<a href="{% url 'blogapp:postdetail' search_data.slug %}">. . . .Read more</a></p>
    <br>
    {% else %}
    

{% endif %}
{% endfor %}

 
  </div>
</div>


{% endblock %}